### ISSUE TITLE
[Data Structures using C/quick_sort.c] Implement a program to sort an array using Quick Sort.

### ISSUE THREAD

**Issue by gopalshibu142** [dscmbcet/hacktoberfest-2022#12]
[Working Directory](https://github.com/dscmbcet/hacktoberfest-2022/tree/main/Data%20Structures%20using%20C)

**Comment by Priyanshu2410** [comment]
I can solve your issue , i am good on both language c++ and JAVA , you should assign me . Thank you

**Comment by iamrahul25** [comment]
Hey, can you please assign this issue to me!
