### ISSUE TITLE
[Object Oriented Programming using Java/Palindrome.java] Add code to check whether a string entered by user is palindrome or not and print result

### ISSUE THREAD

**Issue by BenGeorgeNetto** [dscmbcet/hacktoberfest-2022#14]
[File](https://github.com/dscmbcet/hacktoberfest-2022/blob/main/Object%20Oriented%20Programming%20using%20Java/Palindrome.java) to add code

**Comment by Georgezogos** [comment]
Hello, could you please assing it to me?

**Comment by xditya** [comment]
> Hello, could you please assing it to me?

Hey, this has already been solved [here](https://github.com/dscmbcet/hacktoberfest-2022/commit/bdfce8034bc0603cb2bd18113d7b95a776c1c609)..
